General:
  db_name: "app.db"
  confCheckInterval: 1
  sync: true

Log:
  path: "log.json"
  minSeverity: "info"
  maxAge: 30
  maxSize: 10
  maxFiles: 10

Audit:
  path: "audit.json"
  minSeverity: "info"
  maxAge: 30
  maxSize: 10
  maxFiles: 10

WebServer:
  port: 443
  sslIsEnable: true
  sslCertPath: "cert.pem"
  sslKeyPath: "key.pem"
  sesionTimeout: 600
  initUsername: "admin"
  initPassword: "password"

Sync:
  isEnable: true
  token: "fvdknlvd9ergturoegkvnemc90ru34fcemf340[ijfkdj]"
  members:
    - hostname: "127.0.0.1"
      port: 443
    - hostname: "10.10.10.10"
      port: 8081

Prometheus:
  url: "http://prometheus:8428/api/v1/write"
  metricName: "dns_resolve"
  auth: false
  username: "user"
  password: "password"
  retriesCount: 2
  buferSize: 2

PrometheusLabels:
  opcode: false
  authoritative: false
  truncated: true
  rcode: true
  recursionDesired: false
  recursionAvailable: false
  authenticatedData: false
  checkingDisabled: false
  pollingRate: false
  recursion: true

Resolvers:
  path: "dns_servers.csv"
  pullTimeout: 2
  delimeter: ","
  extraDelimeter: "&"

Watcher:
  location: K2
  securityZone: PROD

